In [2]:
import sys
import numpy as np

In [74]:
# write your code here (for Python default syntax)
ptn_list = [0] * 1000
py_size = sys.getsizeof(ptn_list)
print(py_size)

8056


In [75]:
# write your code here (for numpy syntax)
np_array = np.zeros(1000, dtype=np.int8)
arr_size = np_array.nbytes
print(arr_size)

1000


In [76]:
from numpy import float16

# write your code here
float_array = np.arange(10, dtype=np.float16)
indexes = [0, 2]
print(float_array[indexes])

[0. 2.]


In [11]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
# write your code here
indexes = [1, -1, 4, 0]
print(sum(array[indexes]))

27.0


In [12]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

In [73]:
column = A.mean(axis=0)
print(column)

[2.  8.4]


In [15]:
# write your code here
col = A.std(axis=0)
print(col)

[0.89442719 1.8547237 ]


### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [16]:
sum_y = A.sum(axis=0)
print(sum_y)

[10 42]


### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [17]:
print(A[[0, 1], :])

[[1 6]
 [2 8]]


##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [19]:
print(A[[0, 2, 4], :])

[[ 1  6]
 [ 3 11]
 [ 1  7]]


## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [39]:
# Python code
%timeit v1 = [i for i in range(1000000)]


64.3 ms ± 2.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [38]:
# write your numpy code here and estimate the time of execution
%timeit np_array = np.arange(1000000)


3.1 ms ± 94.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [46]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [i for i in range(1000000)]
vector2 = [i for i in range(1000000)]
result = 0

%timeit unknown_signature(vector1, vector2)
result

80 ms ± 2.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


0

In [58]:
# write your numpy code here and estimate the time of execution
v1 = np.array(vector1)
v2 = np.array(vector2)



In [59]:
%timeit result_np = v1 @ v2

1.17 ms ± 48.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [54]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]
unknown_signature(matrix1, matrix2)

[[5, 12], [21, 32]]

In [55]:
# write your numpy code here and estimate the time of execution
m1 = np.array(matrix1)
m2 = np.array(matrix2)
result = m1* m2
print(result)

[[ 5 12]
 [21 32]]


In [53]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]
unknown_signature(lst)

3.0

In [57]:
# write your numpy code here and estimate the time of execution
arr = np.array(lst)
result = np.mean(arr)
print(result)

3.0


In [63]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [64]:
# write your numpy code here
lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
lst = np.array(lst)
mask = np.array(mask)
lst[mask] = new_value
print(lst)

[0 2 0 4 0]


In [65]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [66]:
list1_np = np.array(list1)
list2_np = np.array(list2)
bitwise_complement_np = ~list1_np
bitwise_and_np = list1_np & list2_np
bitwise_or_np = list1_np | list2_np

print(bitwise_complement_np, bitwise_and_np, bitwise_or_np)


[ -6  -3  -8  -5 -10] [1 2 1 0 8] [ 7  6  7 12 11]


### Task 7.3 Optional

In [67]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [70]:
my_list_np = np.array(my_list)
mask = (my_list_np % 2 == 0) & ((my_list_np % 3 == 0) | (my_list_np > 10))
result_arr = my_list_np[mask]
result = (result_arr ^ 7) + 2
print(result)

[ 3 13 11 21]
